### ISSUE TITLE
Tietokannan luonti automaattisesti

### ISSUE THREAD

**Issue by kakkurij** [kakkurij/SaveSailor#30]

**Comment by kakkurij** [comment]
Tämä sen vuoksi, että uuden kehittäjän ei tarvitse itse ajaa taulujen luontilauseita kantaan. Kannan formaatti kuitenkin pitää olla täysin sama kaikilla, jotta myöhemmin Powerbi:n kanssa ei tule jänniä virheitä

**Comment by ile6695** [comment]
Tähän tarvitaan #29 ja #28
